In [2]:
class Employee:
    empCount = 0
    sal = 0
    def __init__(self, name, family,salary, department):
       self.name = name
       self.family=family
       self.salary= salary
       self.department=department
       Employee.empCount += 1
       Employee.sal = Employee.sal + self.salary
    def displayCount(self):
        print("Total Employee %d" % Employee.empCount)
    def displayEmployee(self):
        print("Name : ", self.name, ", Family: ", self.family," Salary: ", self.salary, ", Department: ", self.department)
    def average(self) :
        sum = 0
        avg = Employee.sal / Employee.empCount
        print("average")
        print(avg)
class FulltimeEmployee(Employee):
  pass
emp1 = Employee("Zara", "sksjs", 200000,"IT")
emp2 = Employee("sara", "skdhdj", 300000,"ITis")
emp3 = FulltimeEmployee("sara", "skdhdj",300000,"ITis")
emp1.displayEmployee()
emp2.displayEmployee()
emp3.displayEmployee()
emp2.average()
print ("Total Employee %d" % Employee.empCount)

Name :  Zara , Family:  sksjs  Salary:  200000 , Department:  IT
Name :  sara , Family:  skdhdj  Salary:  300000 , Department:  ITis
Name :  sara , Family:  skdhdj  Salary:  300000 , Department:  ITis
average
266666.6666666667
Total Employee 3


In [3]:
import requests,json,string
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/Deep_learning"
getdata = requests.get(url)
data = (BeautifulSoup(getdata.content, "html.parser"))
file_content = []
f = open('links_file.txt','w')

# print(data.find('h1',{"class":"firstHeading"}).text)
print(data.find(id='firstHeading').text)

for link in data.find_all('a'):
    if link.has_attr('href') and link.get('href').startswith('/'):
          print(link.text + " : " + link.get('href'))
          file_content.append(link.text + " : " + link.get('href'))
f.write(str(file_content))

Deep learning
Student approaches to learning : /wiki/Student_approaches_to_learning
Artificial neural network : /wiki/Artificial_neural_network
Machine learning : /wiki/Machine_learning
data mining : /wiki/Data_mining
 : /wiki/File:Kernel_Machine.svg
Classification : /wiki/Statistical_classification
Clustering : /wiki/Cluster_analysis
Regression : /wiki/Regression_analysis
Anomaly detection : /wiki/Anomaly_detection
AutoML : /wiki/Automated_machine_learning
Association rules : /wiki/Association_rule_learning
Reinforcement learning : /wiki/Reinforcement_learning
Structured prediction : /wiki/Structured_prediction
Feature engineering : /wiki/Feature_engineering
Feature learning : /wiki/Feature_learning
Online learning : /wiki/Online_machine_learning
Semi-supervised learning : /wiki/Semi-supervised_learning
Unsupervised learning : /wiki/Unsupervised_learning
Learning to rank : /wiki/Learning_to_rank
Grammar induction : /wiki/Grammar_induction
Supervised learning : /wiki/Supervised_learnin

About Wikipedia : /wiki/Wikipedia:About
Disclaimers : /wiki/Wikipedia:General_disclaimer
Contact Wikipedia : //en.wikipedia.org/wiki/Wikipedia:Contact_us
Mobile view : //en.m.wikipedia.org/w/index.php?title=Deep_learning&mobileaction=toggle_view_mobile


44881

In [4]:
import numpy as np
x = np.random.random(20)
print("x:",x)
y=x.reshape(4,5)
print("y:",y)
print("Maximum value replaced by 0:")
print(np.where(y==np.amax(y,axis=1,keepdims=True),0,y))

x: [0.65892165 0.56491316 0.65652251 0.7235068  0.76454999 0.75367166
 0.88864515 0.10382007 0.26658417 0.64151533 0.08869567 0.82515691
 0.94346643 0.79205705 0.49298942 0.97893125 0.35131405 0.63105639
 0.90529434 0.21624131]
y: [[0.65892165 0.56491316 0.65652251 0.7235068  0.76454999]
 [0.75367166 0.88864515 0.10382007 0.26658417 0.64151533]
 [0.08869567 0.82515691 0.94346643 0.79205705 0.49298942]
 [0.97893125 0.35131405 0.63105639 0.90529434 0.21624131]]
Maximum value replaced by 0:
[[0.65892165 0.56491316 0.65652251 0.7235068  0.        ]
 [0.75367166 0.         0.10382007 0.26658417 0.64151533]
 [0.08869567 0.82515691 0.         0.79205705 0.49298942]
 [0.         0.35131405 0.63105639 0.90529434 0.21624131]]
